version: "3"

services:
  node:
    image: offchainlabs/nitro-node:v3.6.8-d6c96a5
    restart: unless-stopped
    #env_file: .env
    ports:
      - "8547:8547" #RPC
      - "8548:8548" #websocket
      - "9642:9642" #sequencer feed
    volumes:
      - ./arbitrum:/home/user/.arbitrum
    command: 
      - --parent-chain.connection.url=https://ethereum-sepolia-rpc.publicnode.com
      - --parent-chain.blob-client.beacon-url=https://eth-beacon-chain.drpc.org
      - --chain.id=421614 
      - --init.latest=pruned 
      - --http.api=net,web3,eth
      - --http.corsdomain=* 
      - --http.addr=0.0.0.0 
      - --http.vhosts=*
