version: "3"

services:
  node:
    image: offchainlabs/nitro-node:v3.6.8-d6c96a5
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:8547:8547" #RPC
      - "127.0.0.1:8548:8548" #websocket
      - "127.0.0.1:9642:9642" #sequencer feed
    volumes:
      - ./arbitrum:/home/user/.arbitrum
    command: 
      - --parent-chain.connection.url=${PARENT_CHAIN_CONNECTION_URL}
      - --parent-chain.blob-client.beacon-url=${PARENT_CHAIN_BLOB_CLIENT_BEACON_URL}
      - --chain.id=${CHAIN_ID}
      - --init.latest=${INIT_LATEST}
      - --http.api=${HTTP_API}
      - --http.corsdomain=${HTTP_CORSDOMAIN}
      - --http.addr=${HTTP_ADDR}
      - --http.vhosts=${HTTP_VHOSTS}
